# Generated by Django 6.0.4 on 2026-05-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stripe_client_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
